### ISSUE TITLE
android 4 > Icon vector drawable not working

### ISSUE THREAD

**Issue by HamedTaherpour** [edgar-zigis/MaterialTextField#4]
Hi
Thanks for your good plugin
But it doesn't work in version 4

Thank you

```
    android.view.InflateException: Binary XML file line #41: Error inflating class com.zigis.materialtextfield.MaterialTextField
        at android.view.LayoutInflater.createView(LayoutInflater.java:626)
        at io.github.inflationx.viewpump.internal.-ViewPumpLayoutInflater.createCustomViewInternal(-ViewPumpLayoutInflater.kt:220)
        at io.github.inflationx.viewpump.internal.-ViewPumpLayoutInflater.access$createCustomViewInternal(-ViewPumpLayoutInflater.kt:19)
        at io.github.inflationx.viewpump.internal.-ViewPumpLayoutInflater$PrivateWrapperFactory2ViewCreator.onCreateView(-ViewPumpLayoutInflater.kt:421)
        at io.github.inflationx.viewpump.internal.-FallbackViewCreationInterceptor.intercept(-FallbackViewCreationInterceptor.kt:14)
        at io.github.inflationx.viewpump.internal.-InterceptorChain.proceed(-InterceptorChain.kt:30)
```

**Comment by edgar-zigis** [comment]
I think that the error is not there, because I am successfully able to append the vector `rightIcon` on my API 17 simulator.
Try adding this: `app:rightIcon = "@drawable/your_vector_icon"`
